### ISSUE TITLE
go test fails

### ISSUE THREAD

**Issue by coxnegative** [fl00r/go-tarantool-1.6#1]
go version go1.2 linux/386

Trying to reproduce tarantool issue 292, "go test" fails with the following error

go test
Connecting to 192.168.1.173:13313 ...
Connected ...
Greeting ... Success
Version: Tarantool 1.6.2-178-gcb78299                                   

--- FAIL: TestClient (0.00 seconds)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
    panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x1 pc=0x810253c]

goroutine 3 [running]:
runtime.panic(0x8164340, 0x82e7788)
    /usr/local/go/src/pkg/runtime/panic.c:266 +0xac
testing.func·005()
    /usr/local/go/src/pkg/testing/testing.go:385 +0xda
runtime.panic(0x8164340, 0x82e7788)
    /usr/local/go/src/pkg/runtime/panic.c:248 +0xef
sync/atomic.AddUint64(0x1862d6ec, 0x1, 0x0, 0x816ba40, 0x0)
    /usr/local/go/src/pkg/sync/atomic/asm_386.s:118 +0xc
_/home/luis/go-tarantool-1%2e6.(_Connection).nextRequestId(0x1862d6e0, 0x0, 0x0)
    /home/luis/go-tarantool-1.6/connection.go:138 +0x55
_/home/luis/go-tarantool-1%2e6.(_Connection).NewRequest(0x1862d6e0, 0x2, 0x1862d720)
    /home/luis/go-tarantool-1.6/request.go:18 +0x51
_/home/luis/go-tarantool-1%2e6.(*Connection).Insert(0x1862d6e0, 0x202, 0x1862d5a0, 0x3, 0x3, ...)
    /home/luis/go-tarantool-1.6/request.go:46 +0x43
_/home/luis/go-tarantool-1%2e6.TestClient(0x186440c0)
    /home/luis/go-tarantool-1.6/tarantool_test.go:38 +0x60b
testing.tRunner(0x186440c0, 0x82e40f8)
    /usr/local/go/src/pkg/testing/testing.go:391 +0x88
created by testing.RunTests
    /usr/local/go/src/pkg/testing/testing.go:471 +0x6d3

goroutine 1 [chan receive]:
testing.RunTests(0x81b9898, 0x82e40f8, 0x1, 0x1, 0x1)
    /usr/local/go/src/pkg/testing/testing.go:472 +0x6ee
testing.Main(0x81b9898, 0x82e40f8, 0x1, 0x1, 0x82e9d20, ...)
    /usr/local/go/src/pkg/testing/testing.go:403 +0x6b
main.main()
    _/home/luis/go-tarantool-1.6/_test/_testmain.go:47 +0x83

goroutine 4 [runnable]:
_/home/luis/go-tarantool-1%2e6.(*Connection).writer(0x1862d6e0)
    /home/luis/go-tarantool-1.6/connection.go:61
created by _/home/luis/go-tarantool-1%2e6.Connect
    /home/luis/go-tarantool-1.6/connection.go:39 +0x29f

goroutine 5 [runnable]:
_/home/luis/go-tarantool-1%2e6.(*Connection).reader(0x1862d6e0)
    /home/luis/go-tarantool-1.6/connection.go:75
created by _/home/luis/go-tarantool-1%2e6.Connect
    /home/luis/go-tarantool-1.6/connection.go:40 +0x2b4
exit status 2
FAIL    _/home/luis/go-tarantool-1.6    0.019s

**Comment by fl00r** [comment]
Ok, it wasn't a good idea to use 64bit requestId.

**Comment by fl00r** [comment]
I've fixed support of 32bit arithmetics, it should work for now on your i386

**Comment by fl00r** [comment]
But my current 1.6.2-197-gb13e482 doesn't work at all %(
It writes that my MSGPACK is invalid on Select OP, ha.

**Comment by fl00r** [comment]
2014-06-02 14:27:31.060 [2029] main request.cc:257 E> ER_INVALID_MSGPACK: Invalid MsgPack - packet body

**Comment by coxnegative** [comment]
same here. Looking in tarantool source code
iproto_constants.cc, line 107, it seems that SELECT only accepts space, limit and key
bit(SPACE_ID) | bit(LIMIT) | bit(KEY),                 /\* SELECT */

**Comment by fl00r** [comment]
Good catch!
Looks like this change was added after this client was created :)
Also, box-protocol is still inconsistent 
https://github.com/tarantool/tarantool/blob/master/doc/box-protocol.txt#L124

I am curioused how to select on secondary indexes now.

**Comment by kostja** [comment]
These are bits for mandatory packet fields, not _all possible_ fields. The protocol doesn't actually limit extra keys, you can pass any unknown key, it will be ignored. But if a driver doesn't give us space id or key, the transaction processor will crash. Hence the check. And we perform the check by filling  a bitmap during parsing and then looking at that bitmap and checking that it has all necessary bits.

**Comment by kostja** [comment]
So the code you're looking at is just a safety measure against a malformed packet, not a restriction on  allowed keys. We made the protocol future-proof by ignoring unknown keys.

**Comment by coxnegative** [comment]
Kosktja comment was pretty useful. Problem is with 

iproto_key_type

and 0x14 (Iterator) key. It expects an UINT, but your code is sending a string.

I guess you should send these, as defined in box/index.h

#define ITERATOR_TYPE(_)                                             \
    /\* ITER_EQ must be the first member for request_create  _/   \
    _(ITER_EQ,  0)       /_ key == x ASC order              _/   \
    _(ITER_REQ, 1)       /_ key == x DESC order             _/   \
    _(ITER_ALL, 2)       /_ all tuples                      _/   \
    _(ITER_LT,  3)       /_ key <  x                        _/   \
    _(ITER_LE,  4)       /_ key <= x                        _/   \
    _(ITER_GE,  5)       /_ key >= x                        _/   \
    _(ITER_GT,  6)       /_ key >  x                        _/   \
    _(ITER_BITS_ALL_SET,     7) /_ all bits from x are set in key      _/ \
    _(ITER_BITS_ANY_SET,     8) /_ at least one x's bit is set         _/ \
    _(ITER_BITS_ALL_NOT_SET, 9) /_ all bits are not set                */ \

**Comment by fl00r** [comment]
That's it. Some time ago it worked with string iterators.
And documentation is not fully covering this aspect ( @kostja ):
https://github.com/tarantool/tarantool/blob/master/doc/box-protocol.txt#L181
:)
@coxnegative,

**Comment by fl00r** [comment]
Ok. That was the original problem of issue https://github.com/tarantool/tarantool/issues/292
Now I send UINT instead of string as iterator and everything is ok.

**Comment by coxnegative** [comment]
Same in my env. All working fine (and damn fast)
